import sys
import os
import streamlit as st
from dotenv import load_dotenv
from langchain_core.messages import AIMessage, HumanMessage

# Add the project's root directory to the Python path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

# Import the agent classes
from agents.web_agent import WebConsultantAgent
from agents.lead_consultant import LeadConsultantAgent, process_uploaded_files_for_tools

# Load environment variables from .env file at the very beginning
load_dotenv()

# --- App UI Configuration ---

st.set_page_config(page_title="AI Business Consultant", layout="wide")
st.title("🤖 AI Business Consultant")
st.markdown("Your intelligent partner for strategic business analysis.")

# --- Initialize Agents ---
@st.cache_resource
def get_web_agent():
    return WebConsultantAgent()

@st.cache_resource
def get_lead_agent():
    return LeadConsultantAgent()

web_agent = get_web_agent()
lead_agent = get_lead_agent()

# --- Mode Selection Sidebar ---
st.sidebar.header("Select Analysis Mode")
analysis_mode = st.sidebar.radio(
    "Choose your consultant's specialty:",
    ("Case Study Analysis", "General Web Consultant", "SWOT Analysis")
)

# --- Render UI for the selected mode ---

if analysis_mode == "Case Study Analysis":
    st.header("🗂️ Case Study Analysis")
    st.markdown("Define a central business question and upload all relevant case files (`.pdf`, `.txt`, `.csv`). The Lead Consultant will perform a comprehensive analysis.")

    case_question = st.text_area("Enter the central business question for this case study:")
    
    uploaded_files = st.file_uploader(
        "Upload your case files (Data Room)",
        type=['pdf', 'txt', 'csv'],
        accept_multiple_files=True
    )

    if st.button("Generate Full Analysis"):
        if not case_question or not uploaded_files:
            st.warning("Please enter a business question and upload at least one file.")
        else:
            with st.spinner("Processing documents and preparing analysis..."):
                process_uploaded_files_for_tools(uploaded_files)
            
            # Clean up any old plot files BEFORE running the agent.
            plot_path = "plot.png"
            if os.path.exists(plot_path):
                os.remove(plot_path)
            
            with st.spinner("Lead Consultant is performing a multi-source analysis... This may take a while."):
                report = lead_agent.run_case_study(case_question)
                st.write("### Lead Consultant's Final Report:")
                st.markdown(report)

                # Check if a NEW plot was generated by the csv_analysis_tool
                if os.path.exists(plot_path):
                    st.image(plot_path)
                    os.remove(plot_path) # Clean up after displaying

elif analysis_mode == "General Web Consultant":
    st.header("🌐 Conversational Web Consultant")
    st.markdown("Ask a question and have a follow-up conversation with the agent.")
    
    # --- FIX APPLIED HERE: Restored the full chat UI logic ---
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    # Display chat messages from history
    for message in st.session_state.chat_history:
        if isinstance(message, AIMessage):
            with st.chat_message("AI"):
                st.write(message.content)
        elif isinstance(message, HumanMessage):
            with st.chat_message("Human"):
                st.write(message.content)

    # Get user input
    user_question = st.chat_input("Ask a question about a company...")
    
    if user_question:
        st.session_state.chat_history.append(HumanMessage(content=user_question))
        with st.chat_message("Human"):
            st.write(user_question)
            
        with st.spinner("Consultant is thinking..."):
            # Pass the history to the agent
            response = web_agent.run_general_consultation(user_question, st.session_state.chat_history)
            
            # Add AI response to history and display it
            st.session_state.chat_history.append(AIMessage(content=response))
            with st.chat_message("AI"):
                st.write(response)

elif analysis_mode == "SWOT Analysis":
    st.header("📊 SWOT Analysis")
    st.markdown("Enter a company name to generate a comprehensive SWOT analysis.")
    company_name = st.text_input("Enter a company name (e.g., Apple, Netflix, Ford):")
    if company_name and st.button(f"Generate SWOT for {company_name}"):
        with st.spinner(f"Performing SWOT analysis for {company_name}..."):
            report = web_agent.run_swot_analysis(company_name)
            st.write(f"### SWOT Analysis: {company_name}")
            st.markdown(report)


st.sidebar.markdown("---")
st.sidebar.info("Project by Chung-Yeh (Oliver) Yang")
